services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: dbfinancialtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend_server
    environment:
      DB_HOST: db
      DB_NAME: dbfinancialtracker
      DB_USER: testuser
      DB_PASSWORD: testpassword
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend/app.py:/app/app.py

  frontend:
    image: nginx:alpine
    container_name: frontend_server
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

volumes:
  postgres_data:
