services:
  db:
    image: postgres:13
    container_name: postgresDb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: dbFinancialTracker
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: backendServer
    environment:
      DB_HOST: db
      DB_NAME: dbFinancialTracker
      DB_USER: testuser
      DB_PASSWORD: testpassword
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend/app.py:/app/app.py

  frontend:
    image: nginx:alpine
    container_name: frontendServer
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

volumes:
  postgresData:
